name: running_action_using_azure_basic_terraform_config 

on:
    push:
      branches: ["*"]


env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: login docker
        uses: docker/login-action@v2.2.0
        with:
            username: ${{ env.DOCKER_USERNAME }}
            password: ${{ env.DOCKER_PASSWORD }}

      - name: build and push   
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            aclgo/test-run_terraform:v${{github.run_number}}
            aclgo/test-run_terraform:latest

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
    
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: fmt terraform
        id: fmt
        run: terraform fmt -check
      
      - name: init terraform
        id: init
        run: terraform init -backend-config="terraform/azure/main.tf"

      - name: validate terraform
        id: validate
        run: terraform validate -no-color
      
      - name: terraform apply
        run: terraform apply -auto-approve -var-file="terraform/azure/terraform.tfvars"
